name: Enforce Branch Name

on:
  create:
  pull_request:

jobs:
  enforce-branch-name:
    name: enforce-branch-name
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4
      - name: ðŸ’‚ Enforce Branch Name
        uses: ./
        with:
          allowed_prefixes: >-
            bugfix,chore,dependabot,docs,feat,feature,fix,hotfix,
            maint,maintain,maintenance,release,renovate
